repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        exclude: ^tests/
        additional_dependencies:
          - beautifulsoup4==4.11.1
          - blueprint==3.4.2
          - botocore==1.24.46
          - certifi==2021.10.8
          - cfgv==3.3.1
          - charset-normalizer==2.0.12
          - click==8.0.4
          - distlib==0.3.4
          - filelock==3.6.0
          - Flask==2.0.3
          - google==3.0.0
          - identify==2.4.12
          - idna==3.3
          - importlib-metadata==4.11.3
          - itsdangerous==2.1.2
          - Jinja2==3.1.1
          - jmespath==1.0.0
          - MarkupSafe==2.1.1
          - nodeenv==1.6.0
          - platformdirs==2.5.2
          - pre-commit==2.18.1
          - protobuf==3.20.1
          - pynamodb==5.2.1
          - pynamodb-attributes==0.3.2
          - python-dateutil==2.8.2
          - python-dotenv==0.20.0
          - PyYAML==6.0
          - requests==2.27.1
          - six==1.16.0
          - soupsieve==2.3.2.post1
          - toml==0.10.2
          - tomli==2.0.1
          - typing_extensions==4.2.0
          - urllib3==1.26.9
          - virtualenv==20.14.1
          - Werkzeug==2.0.3
          - zipp==3.8.0
